spring:
  redis:
    host: 127.0.0.1
    port: 6379
  data:
    mongodb:
      database: practice
      host: localhost
      port: 27017
  jackson:
    default-property-inclusion: non_null
  webclient:
    connection_timeout_millis: 5000
    read_timeout_second: 5
    write_timeout_second: 5
    api_sample_url: http://localhost:8808